[package]
name = "git-blame-pr"
description = "git blame with the PR number"
version = "0.1.0"
edition = "2024"
authors = ["mitsu-ksgr"]
repository = "https://github.com/mitsu-ksgr/git-blame-parser"
license = "MIT"

[dependencies]
git-blame-parser = "0.1.1"
regex = "1.11.1"
